### ISSUE TITLE
about CLS Token

### ISSUE THREAD

**Issue by frensher** [qianwen96/UFDN-Reid#1]
你好,我想请教下
CLS Token这块在论文里面没说吧
我怎么没看到
感觉下面这个分支在论文里面没有体现呢
TDH部分有损失;CDC部分也有损失
下面那个加入类别信息的论述在论文中没看到啊

**Comment by qianwen96** [comment]
cls_token就是示意图里面的decomposing tokens，两个分支在示意图里分别对应了解耦后的特征和所有的解耦特征concat在一起

**Comment by frensher** [comment]
![图片](https://user-images.githubusercontent.com/42425485/185100607-53a2c0d2-7d1c-4a10-9706-4b0293157368.png)
这是并行的两个分支吗,我看论文主要说了tdn和cdc
decomposing token 不是示意图的黑色的部分吗
论文里也没说这个decomposing token是怎么来的吧

>

**Comment by qianwen96** [comment]
这些cls-token和decomposing token都是随机初始化的可学习的，和transformer里面正常的cls-token是一样的。

**Comment by frensher** [comment]
> 这些cls-token和decomposing token都是随机初始化的可学习的，和transformer里面正常的cls-token是一样的。

我想问下,我上图中标记的红框是两个并行的分支嘛
还是说解耦的特征加上cls taken 计算最后的loss

**Comment by michuanhaohao** [comment]
> > 这些cls-token和decomposing token都是随机初始化的可学习的，和transformer里面正常的cls-token是一样的。
> 
> 我想问下,我上图中标记的红框是两个并行的分支嘛 还是说解耦的特征加上cls taken 计算最后的loss

直接数学上的相加，特征的维度不变。

**Comment by frensher** [comment]
> > > 这些cls-token和decomposing token都是随机初始化的可学习的，和transformer里面正常的cls-token是一样的。
> > 
> > 
> > 我想问下,我上图中标记的红框是两个并行的分支嘛 还是说解耦的特征加上cls taken 计算最后的loss
> 
> 直接数学上的相加，特征的维度不变。

3q
