### ISSUE TITLE
about .txt

### ISSUE THREAD

**Issue by frensher** [qianwen96/UFDN-Reid#2]
![图片](https://user-images.githubusercontent.com/42425485/185561647-a77b81bc-300b-4096-856d-408843f932c3.png)
你好,我看三个数据集都这个记事本的要求
但是原始数据集里没有
请问您提供的code能跑吗
还是我理解错了

**Comment by qianwen96** [comment]
这个就是我自己做的一个图片list，我稍后会上传。也可以使用其他开源代码里面的，直接从文件夹遍历读图，本质上都是一样的

**Comment by frensher** [comment]
> 这个就是我自己做的一个图片list，我稍后会上传。也可以使用其他开源代码里面的，直接从文件夹遍历读图，本质上都是一样的

3q

**Comment by frensher** [comment]
> > 这个就是我自己做的一个图片list，我稍后会上传。也可以使用其他开源代码里面的，直接从文件夹遍历读图，本质上都是一样的
> 
> 3q

我试了,还是有点区别的,希望尽快上传.谢谢

**Comment by CarrieYpi** [comment]
> > > 这个就是我自己做的一个图片list，我稍后会上传。也可以使用其他开源代码里面的，直接从文件夹遍历读图，本质上都是一样的
> > 
> > 
> > 3q
> 
> 我试了,还是有点区别的,希望尽快上传.谢谢

我也遇到了同样的问题，希望能尽快上传，感谢！

**Comment by qianwen96** [comment]
readme中已经上传

**Comment by shutarism** [comment]
# ソースコードに関して

- VeRi データセットに対しては学習成功
- VehicleID データセットに対しては、data_listが見つからず実行できず(2023.1.17)

```
  File "./data/datasets/VehicleID.py", line 37, in __init__
    train, num_train_pids, num_train_imgs, num_train_cams, num_train_tids  = self._process_dir(train_path, process_type='train')
  File "./data/datasets/VehicleID.py", line 68, in _process_dir
    with open(list_file, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/qianwen.qian/data/data_list/VehicleID/train_viewpoint_3.list'
```
