### ISSUE TITLE
How to maintain the experimental results for TransReID swin-tiny?

### ISSUE THREAD

**Issue by XiongZhongxia** [qianwen96/UFDN-Reid#5]
Thanks for your insightful work！

I noticed that in your paper, you report results for TransReID with swin-tiny backbone. Could you tell me where to find this implement? Does it contain the jigsaw branch or JPM? I found it's hard to build this module with swin-tiny backbone， given the fact that for local feature branches, it's a token grouping operation in TransReID rather than channel-wise reducing task in your code.

Looking forward to your kind reply. Thanks!

**Comment by qianwen96** [comment]
Sorry, we implemented this by ourselves, and no intention to open source.
